application: 4580117193
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
# Endpoints handler
- url: /_ah/spi/.*
  script: main.api

- url: /.*
  script: main.app

- url: /bootstrap
  static_dir: bootstrap

- url: /media
  static_dir: media

libraries:
# Needed for endpoints/users_id_token.py.
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: 1.0
